#####################################################################################################################################
# OTel Collector
# https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-collector/values.yaml
#####################################################################################################################################

mode: deployment

image:
  repository: "otel/opentelemetry-collector-contrib"

ports:
  # custom port to expose metric receiver, that is called by Prometheus
  prom-exporter:
    enabled: true
    containerPort: 8889
    servicePort: 8889
    protocol: TCP

  # enable internal metrics
  metrics:
    enabled: true

  # disable other services
  jaeger-compact:
    enabled: false
  jaeger-thrift:
    enabled: false
  jaeger-grpc:
    enabled: false
  zipkin:
    enabled: false
  
resources:
  limits:
    cpu: 250m
    memory: 512Mi

# OpenTelemetry Collector configuration
config:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: ${env:MY_POD_IP}:4317
        http:
          endpoint: ${env:MY_POD_IP}:4318

  processors:
    batch:
      send_batch_size: 8192
      timeout: 10s

    resource/traces:
      attributes:
        - key: cluster.environment
          action: upsert
          value: quality-assurance

  exporters:
    debug:
      verbosity: basic

    prometheus:
      endpoint: ${env:MY_POD_IP}:8889

    otlp/jaeger:
      endpoint: jaeger-collector.monitoring:4317
      tls:
        insecure: true

    loki:
      endpoint: https://loki.monitoring:3100/loki/api/v1/push
      default_labels_enabled:
        exporter: false
        job: true

  service:
    pipelines:
      metrics:
        receivers: [otlp]
        processors: [batch]
        exporters: [debug, prometheus]
      traces:
        receivers: [otlp]
        processors: [resource/traces, batch]
        exporters: [debug, otlp/jaeger]
      logs:
        receivers: [otlp]
        processors: [batch]
        exporters: [debug, loki]